# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7881be07f2010a9509d19cbe51b6ef7f94cb59dbac7b5202e5975b047c41f0eb762676cb160c3b504bcf79492fca4f957b524131bc6365906e4e1091eca55e8a

test:
  secret_key_base: 3912257bc80b4fa8530ad86731a19514ceffdf78fe20ca7a66fc86f5d3a696d8c2e88b62d636ea4d103c299c706c555afa1f7f2456b9938808d7cb6d4b07a113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
